### ISSUE TITLE
Добравить набор koans про основы словарей

### ISSUE THREAD

**Issue by Melevir** [moscowpython/learn_python_koans#10]
В нём должно подробненько быть показано, как:
– создавать словари
– получать значение по ключу
– добавлять пару ключ-значение
– варианты действий, если ключа нет (без try...except, его ещё не проходили)
– проверять ключ на вхождение в словарь

**Comment by AnastasiiaNovikova** [comment]
Беру тикет, сделаю до конца субботы.
