### ISSUE TITLE
Добавить набор koans про цикл for

### ISSUE THREAD

**Issue by Melevir** [moscowpython/learn_python_koans#11]
Основы for есть в списках, надо:
– ещё раз их повторить с нуля
– рассказать про break и continue
– показать, что можно итерировать по индексам, а можно сразу по списку
– рассказать про enumerate
– показать, что можно итерировать по строкам, спискам и словарям

**Comment by LadyCaster** [comment]
Возьму, до выходных (могу зацепить один из них)
