### ISSUE TITLE
Логика вопросов по set может быть улучшена. 

### ISSUE THREAD

**Issue by denis-trofimov** [moscowpython/learn_python_koans#23]
Что если привести к похожему виду как задания во всех других темах, чтобы подставлять значение внутрь assert, не в тело теста выше? @Melevir 
Могу сделать сам сегодня. 

https://github.com/moscowpython/learn_python_koans/blob/f9cec55777d5f4def8513f0a74183edbaedec422/koans/about_set.py#L57-L66

Например здесь будет:
set_union = set_A | set_B 
assert set_union ==  ___

**Comment by Melevir** [comment]
Можно.
